### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by jgwinner** [agritheory/htmldemo#1]
Great example, thank you!

What things would you do different with Frappe version 14 or 15?

== John ==

**Comment by agritheory** [comment]
@jgwinner Hey John! All of it, really. [Here's an overview](https://docs.google.com/presentation/d/e/2PACX-1vRYH2-JSZSSFjy99NrUIIB80CNUfV9Nmpa5Jqpxp6jvis6SRbcTHuTPu0B63wioZmaP-KBmrAz9xnT8/pub?start=false&loop=true&delayms=15000) I presented to the US ERPNext community last year.

Micro-templating mechanics are very bad, better to use Vue's templating and reactivity, even if it means more work to get it set up. Of note, every approach demonstrated is not schema driven, meaning that customization is limited to "fork it or start over"

**Comment by jgwinner** [comment]
It's a great presentation, but honestly: 

> All of it, really.

that's why I didn't go through the whole thing :)

Thanks for the pointer! I'll close it.

== John ==
